Hw1
babayanv/tp-advcpp pull request #1
Opened 2020-03-15 20:16 UTC by babayanv

2020-03-16 18:40 UTC, smirnov-vs requested changes

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/examples/echo/src/echo.cpp
> +    size_t length = std::stoul(std::string(buff, 3));
очень больно смотреть, когда числа передаются текстом(
надо бы пофиксить

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +constexpr const int PIPE_FAILED = -1;
const тогда избыточен

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +    constexpr bool isReadable() const;
нет смысла, класс же не может быть constexpr

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +    int m_c2p_fd[2];
тут достаточно хранить 2 дескриптора

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/examples/echo/src/echo.cpp
> +void send(FILE* stream, std::string& msg)
зачем менять строку?

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/examples/echo/src/echo.cpp
> +    return std::string(buff, length);
`{buff, length}`

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/examples/echo/src/main.cpp
> +    if (msg.length() >= 256)
size обычно

2020-03-16 18:40 UTC, smirnov-vs commented on hw1/examples/echo/src/main.cpp
> +    p.write(len_msg, 3);
что если запишет только 2?

2020-03-16 19:52 UTC, babayanv commented on hw1/examples/echo/src/echo.cpp
> +    return std::string(buff, length);
почему такой способ предпочтительнее?

2020-03-16 20:59 UTC, babayanv commented on hw1/examples/echo/src/main.cpp
> +    p.write(len_msg, 3);
все сломается)
Поменял на writeExact

2020-03-16 21:02 UTC, babayanv commented on hw1/examples/echo/src/echo.cpp
> +    size_t length = std::stoul(std::string(buff, 3));
done

2020-03-16 21:02 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr const int PIPE_FAILED = -1;
done

2020-03-16 21:02 UTC, smirnov-vs commented on hw1/examples/echo/src/echo.cpp
> +    return std::string(buff, length);
Текста меньше это самое приятное.
Иногда ещё поможет, когда меняешь string на string_view.
Выходит как с using, меняешь в одном месте тип, а все остальное уже подходит по стандарту.

2020-03-16 21:02 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +    constexpr bool isReadable() const;
done

2020-03-16 21:02 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +    int m_c2p_fd[2];
done

2020-03-16 21:02 UTC, babayanv commented on hw1/examples/echo/src/echo.cpp
> +void send(FILE* stream, std::string& msg)
Незачем)
добавил const

2020-03-16 21:04 UTC, babayanv commented on hw1/examples/echo/src/main.cpp
> +    if (msg.length() >= 256)
Как я понял, для совместимости с другими контейнерами. Сами по себе они работают одинакого.
Поменял на size()

2020-03-16 21:08 UTC, smirnov-vs requested changes

2020-03-16 21:08 UTC, smirnov-vs commented on hw1/examples/echo/src/main.cpp
> +    p.writeExact(&msg_length, sizeof(size_t));
Предлагаю добавить ещё перегрузку шаблонную, которая умеет грузить pod типы, не придётся писать всегда sizeof

2020-03-16 21:08 UTC, smirnov-vs commented on hw1/examples/echo/src/main.cpp
> +    p.readExact(buff, msg_length);
Что если длина больше 256?

2020-03-16 21:08 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +    void initAsParent(int (&p2c_fd)[2], int (&c2p_fd)[2]);
Давай эти массивы лучше в using, а то выглядит страшненько

2020-03-17 16:27 UTC, a-badin reviewed
Код мне понравился, здорово что есть noexcept деструктор и свой класс исключений.
Сильно удивляет блок с константами для обработки ошибок со значениями -1.
Даже если бы функция возвращала не один код ошибки а несколько, смысл в таких константах был бы, только в случае если бы мы обрабатывали не все а только часть ошибок. Если мы обрабатываем только сам факт, что ошибка есть, достаточно просто проверить что вернулось число меньше 0. Читаемость кода не пострадает

2020-03-17 16:27 UTC, a-badin commented on hw1/process/CMakeLists.txt
> +project(${PROC_LIB_NAME} CXX)
Обычно если указывается project в подпроекте - значит это самостоятельный проект и его можно собрать из этой директории. Нужно продублировать cmake_minimum_required

2020-03-17 16:27 UTC, a-badin commented on hw1/examples/echo/CMakeLists.txt
> +project(${EX_ECHO_NAME} CXX)
Тоже про под-проекты в проетке. Если это новый проект, то он должен уметь собираться самостоятельно

2020-03-17 16:27 UTC, a-badin commented on hw1/examples/CMakeLists.txt
> +project(examples)
Необязательно создавать по CMakeLists.txt в каждой директории,
Можно сразу из корневого CMakeLists.txt указать add_subdirectory(examples/echo)

2020-03-17 16:27 UTC, a-badin commented on hw1/examples/echo/CMakeLists.txt
> +    PRIVATE
Когда линкуем к исполняемым файлам можно не писать PRIVATE|PUBLIC|INTERFACE, ведь исполняемый файл никогда не будет зависимостью другого исполняемого файла или библиотеки

2020-03-17 16:27 UTC, a-badin commented on hw1/examples/echo/src/main.cpp
> +        proc::Process proc("./echo_child");
Ну очень странно хардкодить путь до файла, даже не вынесено в константу. Все же лучше параметром передать путь

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +    int p2c_fd[2] = {0};
Если ввели алиас на Pipe, так почему его здесь не использовать. Pipe p2c_fd{};
Если Pipe поменяется, например, на отдельный класс, тут не придется ничего менять

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +    case FORK_FAILED:
Обычно константы выносят, чтобы их можно было легко поменять, например, имя директории, размер буффера,  цвет кнопки, имя шрифта. Константу FORK_FAILED поменять не получится - программа перестанет работать и это зависит от стандарта POSIX. Условие m_pid < 0 поймет любой программист, как что нас интересует случай, что что-то пошло не так, но нам не важно что именно.

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +        initAsChild(path, p2c_fd, c2p_fd);
Switch практически не имеет преимуществ по сравнению с if'ом. Без констант код не потеряет читабельности так как используются отличные названия методов класса

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +    default:
Лучше явно указать условие при котором мы вызываем initAsParent

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +        bytes_read += read(buff_begin, len - bytes_read);
Если пайп закроется до передачи всего сообщения - будет вечный цикл. Нужно тоже кидать исключение

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +    waitpid(m_pid, NULL, 0);
kill и waitpid может выдать ошибку, нужно ее обрабатывать. Мы можем кинуть тут исключение, главное поймать его в деструкторе

2020-03-17 16:27 UTC, a-badin commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
Кажется что эти константы используются только в реализации класса, можно вынести их в cpp как static'и

2020-03-17 16:27 UTC, a-badin commented on hw1/process/src/Process.cpp
> +        bytes_written += write(buff_begin, len - bytes_written);
Если родитель закроет пайп раньше времени, write будет спамить 0 и мы зациклимся

2020-03-17 21:25 UTC, babayanv commented on hw1/examples/CMakeLists.txt
> +project(examples)
Это на случай, если появятся новые примеры. Достаточно будет просто добавить сюда под-директорию и отдельный CMakeLists.txt для нового примера. Думаю, так будет удобнее, поэтому пока оставлю как есть)

2020-03-17 21:25 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    int p2c_fd[2] = {0};
Сыглы, просмотрел. Поправил)

2020-03-17 21:32 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    case FORK_FAILED:
Сделал это, чтобы избавиться от магических чисел. Поменял на if и избавился от констант. Надеюсь, так вышло более вербозно

2020-03-17 21:32 UTC, babayanv commented on hw1/process/src/Process.cpp
> +        initAsChild(path, p2c_fd, c2p_fd);
переделал

2020-03-17 21:33 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
Можно перенести в cpp, но какой смысл добавлять static? Как я понимаю, разницы не будет никакой в данном случае

2020-03-17 22:00 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    case FORK_FAILED:
Ну и для того, чтобы было сразу понятно, чему соответствует тот или иной возврат без необходимости лезть в маны.

Убрал константы для форка, остальные пока оставил

2020-03-17 22:25 UTC, babayanv commented on hw1/process/src/Process.cpp
> +        bytes_written += write(buff_begin, len - bytes_written);
Судя по [ману](https://linux.die.net/man/2/write), при попытке записи в не открытый для записи файловый дескриптор, вернется ошибка. В таком случае write, который метод класса, кинет исключение. То есть бесконечного цикла не случится.

```
Return Value
On success, the number of bytes written is returned (zero indicates nothing was
written). On error, -1 is returned, and errno is set appropriately.

If count is zero and fd refers to a regular file, then write() may return a
failure status if one of the errors below is detected. If no errors are detected,
0 will be returned without causing any other effect. If count is zero and fd 
refers to a file other than a regular file, the results are not specified. 
...
EBADF
    fd is not a valid file descriptor or is not open for writing. 
```

2020-03-17 22:27 UTC, babayanv commented on hw1/process/src/Process.cpp
> +        bytes_read += read(buff_begin, len - bytes_read);
Аналогично write. Тут должно вылететь исключение из метода Process::read, из-за попытки чтения из не открытого на чтение дескриптора

2020-03-17 22:52 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    waitpid(m_pid, NULL, 0);
Сделал.
Вообще хотел спросить, насколько целесообразно здесь использовать исключения для обработки ошибок? Везде, кроме конструктора, можно обойтись простым кодом возвратом из метода. Это вроде как посимпотнее должно выйти

2020-03-17 22:52 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    default:
Сделал

2020-03-17 22:59 UTC, babayanv commented on hw1/process/CMakeLists.txt
> +project(${PROC_LIB_NAME} CXX)
done

2020-03-17 23:00 UTC, babayanv commented on hw1/examples/echo/CMakeLists.txt
> +project(${EX_ECHO_NAME} CXX)
done

2020-03-17 23:00 UTC, babayanv commented on hw1/examples/echo/src/echo.cpp
> +    return std::string(buff, length);
done

2020-03-17 23:10 UTC, babayanv commented on hw1/examples/echo/CMakeLists.txt
> +    PRIVATE
Сделал

2020-03-17 23:25 UTC, babayanv commented on hw1/examples/echo/src/main.cpp
> +        proc::Process proc("./echo_child");
Сделал. Путь к файлу теперь передается аргументом кс

2020-03-17 23:34 UTC, babayanv commented on hw1/examples/echo/src/main.cpp
> +    p.readExact(buff, msg_length);
В текущей версии ни сообщение длиной более 255, ни его длина бы просто не отправились, так как функции отправки преверяют на длину. Соответсвенно, здесь бы исполнение заблокалось, пока в stdin родительского процесса не запишут сообщение короче 256

Но на всякий стал выделять этот массив на куче)

2020-03-17 23:39 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
Перенес

2020-03-18 01:13 UTC, babayanv commented on hw1/examples/echo/src/main.cpp
> +    p.writeExact(&msg_length, sizeof(size_t));
Сделал методы, которым необходимо передать толькоуказатель без размера. Работает только для pod-типов

2020-03-18 01:14 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    case FORK_FAILED:
После добавления шаблонных методов пришлось вернуть обратно в hpp, так как они там тоже используются)

2020-03-18 01:16 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
После добавления шаблонных методов пришлось вернуть обратно в hpp, так как они там тоже используются)

2020-03-18 01:16 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
После добавления шаблонных методов пришлось вернуть обратно в hpp, так как они там тоже используются)

2020-03-18 01:32 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
Кароч, в какой-то момент я понял, что это говнище и просто выпилил все константы)

2020-03-18 01:33 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +constexpr int PIPE_FAILED = -1;
Кароч, в какой-то момент я понял, что это говнище, и просто избавился от всех констант)

2020-03-18 01:35 UTC, babayanv commented on hw1/process/include/process/Process.inl
> +}
Не совсем уверен, что так делать корректно, но пока ничего другого не придумал)

Хотелось бы услышать ваше мнение

2020-03-18 01:36 UTC, babayanv commented on hw1/process/include/process/Process.inl
> +        const void* buff_begin = reinterpret_cast<const char*>(data) + bytes_written;
Не совсем уверен, что так делать корректно, но пока ничего другого не придумал)

Хотелось бы услышать ваше мнение

2020-03-18 20:29 UTC, smirnov-vs commented on hw1/examples/echo/src/main.cpp
> +    p.readExact(buff, msg_length);
проще сделать как-то так
```
std::string received_msg;
received_msg.resize(msg_length);
```

а потом записать туда через `.data()` и `.size()`
минус одно копирование)

2020-03-18 20:31 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +    void readExact(DataType* data);
в c++ ссылки всегда предпочтительнее

2020-03-18 20:33 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +    void readExact(DataType* data);
эти методы стоит назвать просто read и write, оставить 2, а внутри они будут вызывать Exact методы  
не может быть ситуации, что ты попросил скачать тебе от size_t половинку или хотя бы 1 байт)

2020-03-18 20:33 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +        class = typename std::enable_if<std::is_pod<DataType>::value>::type
предпочтительнее сократить через enable_if_t и is_pod_v

2020-03-18 23:17 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +        class = typename std::enable_if<std::is_pod<DataType>::value>::type
сделал

2020-03-18 23:30 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +    void readExact(DataType* data);
Поменял тип с указателя на ссылку

> не может быть ситуации, что ты попросил скачать тебе от size_t половинку или хотя бы 1 байт)
Это понятно. А что если заданный тип - структура из нескольких подов. Не произойдет ли ситуации, когда считаются не все поля?

2020-03-18 23:49 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +    void readExact(DataType* data);
Оставил 2 метода read и write

2020-03-18 23:57 UTC, babayanv commented on hw1/examples/echo/src/main.cpp
> +    p.readExact(buff, msg_length);
Сделал так, но по факту же выходит то же самое?)

2020-03-19 09:00 UTC, smirnov-vs commented on hw1/process/include/process/Process.hpp
> +    void readExact(DataType* data);
структура из нескольких полей это просто последовательность байт, просто компилятор указывает, с каким оффсетом какое поле можно прочесть, ну и он знает сколько байт для каждого поля можно считать

2020-03-19 09:15 UTC, smirnov-vs commented on hw1/process/include/process/Process.inl
> +        const void* buff_begin = reinterpret_cast<const char*>(data) + bytes_written;
у тебя уже есть методы Exact
осталось написать что-то типа
```
template <class T>
T read()
{
  T value;
  readExact(&value, sizeof(value))
  return value;
}
```

2020-03-19 09:23 UTC, babayanv commented on hw1/process/include/process/Process.inl
> +        const void* buff_begin = reinterpret_cast<const char*>(data) + bytes_written;
Йеп, на что-то такое уже переделал. Там была опечатка с неиспользованной локальной переменной. Только что поправил)

2020-03-19 09:58 UTC, smirnov-vs commented on hw1/process/include/process/Process.inl
> +    static constexpr size_t data_size = sizeof(DataType);
столько слов написал, когда достаточно было написать sizeof ниже прямо в метод)

во-первых, какой смысл делать static переменную, тратятся ресурсы на thread-safe once инициализацию каждый раз, хотя sizeof сам по себе только зашивает в код программы константу
на стек записать константу из области данных было бы быстрее

во-вторых от компилятора ожидается, что эти методы будут инлайниться, так как это просто синтаксический сахар для программиста
чтобы компилятору помочь, методы сразу пишутся в определении класса, чтобы они были по дефолту inline, шаблоны выделять в отдельный файл не принято

метод использует writeExact, который может кинуть исключение, тут возвращать можно void

2020-03-19 10:42 UTC, babayanv commented on hw1/process/include/process/Process.inl
> +    static constexpr size_t data_size = sizeof(DataType);
Поправил sizeof. Поменял возвращаемое значение на void.

Почему выносить определение шаблонов в отдельный файл не принято? Есть какие-то функциональные различия кроме iniline или так просто красивее?

По поводу inline не совсем понял.
В прошлой версии файл Process.inl инклюдился прямо в Process.hpp. То есть, по сути, для линковщика объявление и определение шаблонных методов находились в одном пространстве, иначе линкер бы кинул ошибку. Насколько я знаю, шаблонные методы по дефолту не являются inline. По крайней мере, в стандарте на этот счет ничего не нашел. То есть, если я не ошибаюсь, для того, чтобы сделать эти методы инлайновыми, достаточно было просто добавить спецификатор inline в их определение в файле Process.inl.
По поводу этого не уверен, поэтому перенес определение методов в определение класса)

2020-03-19 10:49 UTC, smirnov-vs commented on hw1/process/include/process/Process.inl
> +    static constexpr size_t data_size = sizeof(DataType);
насчет выноса шаблонов - обычно их пишут в хедерах там где они объявлены, такое соглашение у разработчиков, кода выходит в сумме меньше

насчет inline
шаблонные функции должны быть inline по дефолту, так как иначе будут проблемы с линковкой, а инлайн гарантирует что будет только один экземпляр функции на всю программу
шаблонные методы строго говоря, тоже должны быть всегда inline, даже если ты их разнес
но привычнее видеть их прямо в определении класса т.к. все методы, реализованные внутри класса, по дефолту уже inline
плюс кода писать надо меньше

стоит еще помнить что специализация шаблона уже не inline и точно вызовет проблемы линковки

2020-03-19 10:51 UTC, smirnov-vs approved these changes
@a-badin, я тут все, завершай свою часть и ставь баллы

2020-03-26 07:01 UTC, a-badin commented on hw1/process/src/Process.cpp
> +    waitpid(m_pid, NULL, 0);
В первую очередь нужно остановиться на чем-то одном. То есть если мы отказываемся от исключений, то нужно везде, где могут кидаться исключения, ловить их и возвращать код ошибки, чтобы не было винегрета. С++ нам предлагает исключения, так как весь код стандартной библиотеки им пользуется.

2020-03-26 07:08 UTC, a-badin commented on hw1/process/src/Process.cpp
> +        bytes_read += read(buff_begin, len - bytes_read);
Я согласен с вами, но все же это странно: read вам явно говорит о том, что мы достигли конца файла, возвращая 0. Вы игнорируете это, и отправляетесь на следующую итерацию цикла и пытаетесь прочитать файл еще раз, чтобы точно получить ошибку.

2020-03-26 07:46 UTC, a-badin requested changes

2020-03-26 07:46 UTC, a-badin commented on hw1/process/include/process/Exception.hpp
> +    const char* what() const noexcept {
Хорошо еще написать override

2020-03-26 07:46 UTC, a-badin commented on hw1/process/include/process/Process.hpp
> +        class = typename std::enable_if_t<std::is_pod_v<DataType>>
typename после = можно не писать.
Обратите внимание, что если вы захотите определить еще одну перегрузку write, у вас будет ошибка
Секция Notes https://en.cppreference.com/w/cpp/types/enable_if

2020-03-26 07:46 UTC, a-badin commented on hw1/process/src/Process.cpp
> +        throw BadProcess();
Пайпы остались открытыми

2020-03-26 07:46 UTC, a-badin commented on hw1/process/src/Process.cpp
> +    m_p2c_fd = std::exchange(other.m_p2c_fd, -1);
А если у this в этот момент были открытые пайпы или запущенные процессы, кто их закроет?

2020-03-26 13:15 UTC, babayanv commented on hw1/process/include/process/Exception.hpp
> +    const char* what() const noexcept {
Сделал

2020-03-26 13:28 UTC, babayanv commented on hw1/process/src/Process.cpp
> +        throw BadProcess();
перед броском исключения теперь закрываю пайпы

2020-03-26 13:29 UTC, babayanv commented on hw1/process/src/Process.cpp
> +    m_p2c_fd = std::exchange(other.m_p2c_fd, -1);
Добавил метод safeStop, который вызываю в деструкторе и здесь перед заменой

2020-03-26 13:35 UTC, babayanv commented on hw1/process/include/process/Process.hpp
> +        class = typename std::enable_if_t<std::is_pod_v<DataType>>
Убрал typename, но остальное оставил, так как не предусматривал возможности еще одних перегрузок для read и write. Не думаю, что он может корректно отработать не для POD-типов

2020-03-26 18:30 UTC, merged