Hw3
babayanv/tp-advcpp pull request #3
Opened 2020-03-31 15:40 UTC by babayanv

2020-04-03 16:27 UTC, a-badin requested changes
Код классный, замечаний немного.
Рекомендую писать методы так, чтобы воспользоваться методом правильно было легко, а неправильно сложно.

2020-04-03 16:27 UTC, a-badin commented on hw3/CMakeLists.txt
> +project(hw2 CXX)
hw3 наверное

2020-04-03 16:27 UTC, a-badin commented on hw3/examples/CMakeLists.txt
> +project(examples)
Уже обсуждали

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    connect(m_dst_addr, m_dst_port);
Если connect кинет исключение - m_sock_fd не закроется

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    m_dst_addr = dst_addr;
Нарушение базовой безопасности исключения, при ошибке m_dst_addr ведет на неверный адрес

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    if (::connect(m_sock_fd,
А если Connection уже подключен - будет ошибка, надо вызвать close

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    ::close(m_sock_fd);
Я эту ошибку не увидел у вас и в классе Process, если после вызова close() создать файл, номер m_sock_fd перейдет этому файлу и тогда Connection сможет писать в чужой файл + он 100% его закроет в дестуркторе. Нужно выставлять в какой нибудь -1

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +        throw SocketError("Socket file descriptor is closed: ");
возврат 0 не является ошибкой

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +        bytes_read += read(buff_begin, len - bytes_read);
А вот тут возврат 0 является ошибкой, вы же вызвали метод считать ровно len байтов, а он этого сделать не смог

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    m_dst_addr = std::move(other.m_dst_addr);
std::exchange(other.m_dst_addr, {});

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +                  static_cast<in_port_t>(m_dst_addr.size())) == nullptr)
В другом месте вы сравниваете с != 0, почему nullptr?

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    ::close(m_sock_fd);
Если прям вот совсем быть аккуратным, лучше проверять ошибку на выходе из close

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/include/tcp/Exception.hpp
> +    explicit SocketError(const char* what_arg);
у вас у string имеет implicit конвертор в char* достатоно одного

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Server.cpp
> +    m_opened = true;
А listen

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Server.cpp
> +    ::close(m_sock_fd);
m_sock_fd в невалидное

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/src/Server.cpp
> +    return Connection(std::move(conn_fd), client_addr);
первый раз пробовал std::move вызвать у int'а - у меня conn_fd остался прежним. Предлагаю просто передавать по значению

2020-04-03 16:27 UTC, a-badin commented on hw3/tcp/include/tcp/Connection.hpp
> +    Connection(int&& sock_fd, const sockaddr_in& sock_info);
Я вам рекомендую положить этот метод в приватные. И сделать Server friend'ом у Connection.
Сторонний программист может вызвать этот метод с любым числом в качестве sock_fd, например, так:
Connection con(open("123.txt", O_RDWR), {});

2020-04-03 19:35 UTC, babayanv commented on hw3/CMakeLists.txt
> +project(hw2 CXX)
Сделал

2020-04-03 19:35 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +    connect(m_dst_addr, m_dst_port);
Поправил

2020-04-03 19:36 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +    m_dst_addr = dst_addr;
Поменял порядок. Теперь сначала все системные выховы - потом переписываю поля

2020-04-03 19:36 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +    ::close(m_sock_fd);
Сделал

2020-04-03 19:36 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +        throw SocketError("Socket file descriptor is closed: ");
Перенес в readExact

2020-04-03 19:37 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +        bytes_read += read(buff_begin, len - bytes_read);
Сделал

2020-04-03 19:37 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +    m_dst_addr = std::move(other.m_dst_addr);
Зачем, это же всего лишь строка? Не вижу смысла ее перетирать

2020-04-03 19:38 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +                  static_cast<in_port_t>(m_dst_addr.size())) == nullptr)
nullptr, тк inet_ntop возвращает указатель. Остальные функции возвращаели инт, поэтому там сравниваю с 0

2020-04-03 19:38 UTC, babayanv commented on hw3/tcp/include/tcp/Exception.hpp
> +    explicit SocketError(const char* what_arg);
Убрал тот, который принимает const char*, оставил со string

2020-04-03 19:38 UTC, babayanv commented on hw3/tcp/src/Server.cpp
> +    ::close(m_sock_fd);
сделал

2020-04-03 19:40 UTC, babayanv commented on hw3/tcp/src/Server.cpp
> +    return Connection(std::move(conn_fd), client_addr);
Я это сделал для того, чтобы переданный дескриптор захватывался Connection и извне нельзя было писать в него. Так как теперь он приватный, смысла в этом нет, поэтому теперь просто передаю по значению

2020-04-03 19:43 UTC, babayanv commented on hw3/tcp/include/tcp/Connection.hpp
> +    Connection(int&& sock_fd, const sockaddr_in& sock_info);
Сделал так, но мне не оч понравилось такое решение.

Мне кажется, лучше было оставить этот конструктор публичным. Если пользователь передаст в него какие-то случайных данные, то ему прилетит исключение. С тем же успехом туда можно просто передать какой-нибудь рандомный инт, как и в случае с остальными конструкторами. В таком случае это вина самого пользователя.

2020-04-03 19:58 UTC, babayanv commented on hw3/tcp/src/Connection.cpp
> +    if (::connect(m_sock_fd,
Сделал

2020-04-03 20:03 UTC, babayanv commented on hw3/tcp/src/Server.cpp
> +    m_opened = true;
Добавил

2020-04-03 20:28 UTC, babayanv commented on hw3/examples/CMakeLists.txt
> +project(examples)
поправил

2020-04-07 10:29 UTC, a-badin commented on hw3/tcp/src/Connection.cpp
> +    m_dst_addr = std::move(other.m_dst_addr);
Да, я почему то подумал, что это какая-то сложная структура

2020-04-07 10:29 UTC, a-badin commented on hw3/tcp/include/tcp/Connection.hpp
> +    Connection(int&& sock_fd, const sockaddr_in& sock_info);
Вы все правильно говорите, но С++ нам позволяет наставить таких заборов, чтобы пользователь вашего API получил ошибку еще на этапе компиляции, а не во время выполнения.

2020-04-07 10:35 UTC, a-badin approved these changes

2020-04-07 10:35 UTC, merged