Hw4
babayanv/tp-advcpp pull request #4
Opened 2020-04-10 06:27 UTC by babayanv

2020-04-10 18:56 UTC, smirnov-vs requested changes

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +                if (conn.read(msg.data(), msg.size()) == 0)
может не дочитать до конца
попробуй читать мегабайт

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +                server.fdReadyToRead(conn.fd());
эти методы у conn

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +    server.init(argv[1], strtoul(argv[2], NULL, 10), atoi(argv[3]), handler);
конструктор

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +    server.init(argv[1], strtoul(argv[2], NULL, 10), atoi(argv[3]), handler);
разнести парсинг argv

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +    server.init(argv[1], strtoul(argv[2], NULL, 10), atoi(argv[3]), handler);
std::string_view std::from_chars

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +            continue;
это задача вызывающего процесс скрипта

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/epoll_server/include/epoll_server/Server.hpp
> +    std::map<int, Connection> m_connections;
лучше хэш
еще одна оптимизация - `unordered_set` std::hash + operator==

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/epoll_server/src/Connection.cpp
> +    m_dst_port = std::exchange(other.m_dst_port, -1);
есть ли разница со swap?

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/epoll_server/include/epoll_server/Server.hpp
> +              Callback&& do_handle_client = [](Connection&){});
необязательно rvalue

2020-04-10 18:56 UTC, smirnov-vs commented on hw4/epoll_server/src/Server.cpp
> +    : m_do_handle_client(std::forward<Callback>(do_handle_client))
форвард только для форвард ссылок

2020-04-11 22:33 UTC, babayanv commented on hw4/epoll_server/include/epoll_server/Server.hpp
> +    std::map<int, Connection> m_connections;
По поводу unordered_set. Его тут в текущей реализации юзать не удобно. Связано это с тем, что epoll_wait даст мне чистый файловый дескриптор. В set ключ - это Connection. Поиск можно произвести только по ключу, поэтому в данной реализации возможен только гетерогенный поиск по инту (то есть, я перегружаю функторы хеширования и сравнения на все вариации использования Connection и int друг с другом). Но такую штуку добавили только в 20 стандарте, при чем она доступна только для msvc на данный момент.

https://en.cppreference.com/w/cpp/compiler_support
```Heterogeneous lookup for unordered containers```

Как альтернативу можно:
1. Заюзать хэш мапу, вместо множетсва.
2. Ваще убрать контейнер с подключениями и конструировать Connection из полученного дескриптора на месте, собирая инфу об адресе и порте подключения из getsockopt.

В принципе смысла в контейнере уже не вижу, поэтому сделал 2 варик

2020-04-11 22:33 UTC, babayanv commented on hw4/examples/echo/src/server.cpp
> +            continue;
Сделал

2020-04-11 22:34 UTC, babayanv commented on hw4/examples/echo/src/server.cpp
> +    server.init(argv[1], strtoul(argv[2], NULL, 10), atoi(argv[3]), handler);
Сделал

2020-04-11 22:34 UTC, babayanv commented on hw4/examples/echo/src/server.cpp
> +                server.fdReadyToRead(conn.fd());
Сделал

2020-04-12 00:26 UTC, babayanv commented on hw4/examples/echo/src/server.cpp
> +            continue;
Точнее, убрал)

2020-04-12 00:48 UTC, babayanv commented on hw4/epoll_server/src/Connection.cpp
> +    m_dst_port = std::exchange(other.m_dst_port, -1);
Есть.
```c++
exchange(a, b);```
запишет b в a и вернет старое значение а.
```c++
swap(a, b);```
запишет a в b и b в a, при этом ничего не вернет. Более того, он принимает только lvalue ссылки на объекты одного типа, то есть `std::swap(other.m_dst_port, -1);` просто не скомпилируется.
exchange в свою очередь может принимать аргументы разных типов и под капотом просто мувает второй аргумент к rvalue и использует оператор переноса.

В данном случае лучше подходит exchange

2020-04-12 00:59 UTC, babayanv commented on hw4/epoll_server/include/epoll_server/Server.hpp
> +              Callback&& do_handle_client = [](Connection&){});
Это делает возможным инициализацию без выделения функции на стеке.

То есть можно будет написать не только
```c++
auto handler = [](){...};
Server::init(..., handler);
```

, но и
```c++
Server::init(..., [](){...});
```

Без rvalue единственный способ так сделать - это принимать Callback по значению. Тогда будет сначала вызван конструктор переноса std::function для аргумента функции, потом конструктор копирования для поля колбека

2020-04-12 01:16 UTC, babayanv commented on hw4/epoll_server/src/Server.cpp
> +    : m_do_handle_client(std::forward<Callback>(do_handle_client))
Без forward для m_do_handle_callback независимо от того, какой аргумент был передан в конструктор, будет вызван конструктор копирования. С forward будет выбран соответствующий переданному значению конструктор. То есть:

* Без forward в обоих вариантах вызова:
```c++
auto handler = [](){...};
Server serv(..., handler);
```
и
```c++
Server serv(..., [](){...});
```
вызовится конструктор копирования - std::function(const std::function&);

* С forward:
для 
```c++
auto handler = [](){...};
Server serv(..., handler);
```
вызовится конструктор копирования, а для
```c++
Server serv(..., [](){...});
```
вызовится конструктор переноса - std::function(std::function&&)

2020-04-12 09:40 UTC, babayanv commented on hw4/examples/echo/src/server.cpp
> +                if (conn.read(msg.data(), msg.size()) == 0)
Сделал. Сохраняю прочитанные данный в Connection::input_registry. Когда размер сохраненных данных достигает 1 MB, отправляю обратно

2020-04-14 23:38 UTC, smirnov-vs commented on hw4/epoll_server/include/epoll_server/Server.hpp
> +              Callback&& do_handle_client = [](Connection&){});
`const Callback&`?
твой конструктор принимает только rvalue, lvalue не работает

ты стал жертвой оптимизации
лямбда твоя заинлайнилась туда как rvalue, даже если она раньше на стеке была как lvalue
соответственно у тебя первый случай строго говоря нерабочий, тебе повезло
попробуй, например лямбду превратить в function заранее, не всегда же это лямбда будет в общем случае

2020-04-14 23:43 UTC, smirnov-vs commented on hw4/epoll_server/src/Server.cpp
> +    : m_do_handle_client(std::forward<Callback>(do_handle_client))
да, так как он работает в этом случае примерно также как мув

в любом случае возвращаясь к теме - форвард можно вызывать только для форвард ссылок, тут он неуместен, нужен мув

2020-04-16 00:16 UTC, babayanv commented on hw4/epoll_server/include/epoll_server/Server.hpp
> +              Callback&& do_handle_client = [](Connection&){});
Понял. Думал, это по-другому работает. Сделал через const ссылку

2020-04-16 00:17 UTC, babayanv commented on hw4/epoll_server/src/Server.cpp
> +    : m_do_handle_client(std::forward<Callback>(do_handle_client))
Да, опять не туда подумал)
Поменял на move

2020-04-19 16:38 UTC, smirnov-vs commented on hw4/examples/echo/src/server.cpp
> +                if (conn.read(msg.data(), msg.size()) == 0)
и приходят прямо те же данные?) байт в байт?

2020-04-19 23:03 UTC, babayanv commented on hw4/examples/echo/src/server.cpp
> +                if (conn.read(msg.data(), msg.size()) == 0)
Ну да
![hw4](https://user-images.githubusercontent.com/32416153/79702115-0dc11e80-82ab-11ea-907b-b0fe156befcc.png)

2020-04-20 10:13 UTC, smirnov-vs approved these changes

2020-04-20 10:13 UTC, merged