Hw5
babayanv/tp-advcpp pull request #5
Opened 2020-04-16 00:05 UTC by babayanv

2020-04-21 08:11 UTC, a-badin requested changes
Вы частично повторяете логику std::allocator_traits, если вам хочется выделять память под свои объекты через свой аллокатор, можете обернуть LinearAllocator в std::allocator_traits и пользоваться готовыми методами

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        reinterpret_cast<T*>(mmap_ptr),
из void* кастится через static_cast

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        , m_unused_memory_begin_ptr(
Есть смысл делать constructor member initializer lists у сложных типов, чтобы съэкономить на инициализации с конструктором по-умолчанию.
Когда у вас типы обычные указатели, лучше вынести их инициализацию в тело конструктора, тем более что инициализация не тривиальная.

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +    const long c_page_size = ::sysconf(_SC_PAGE_SIZE);
зачем держать это в теле класса + unsigned

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +    boundary_ptr* m_unused_memory_begin_ptr;
Возможно было бы проще хранить один указатель на структуру, так как они у вас находятся в одном месте, идут друг за другом. Их было бы проще инициализировать и передавать в move

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        return *m_unused_memory_begin_ptr;
не совсем понятно зачем выделять геттер в private секции

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/allocator/LinearAllocator.hpp
> +    constexpr LinearAllocator(const LinearAllocator<U>& other)
этот метод покрывает верхний

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/container/Map.hpp
> +template <class Key, class T, uint AccessorsCount = 1, class Compare = std::less<Key>>
Зачем добавлять параметр AccessorsCount. Любое значение кроме 1, дает вам race condition

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/container/Map.hpp
> +    using key_type = Key;
Назовите сразу как вам хочется в аргументах

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +    constexpr Semaphore(uint accessors_count = 1)
Что делает constexpr в этом месте?

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +            destroy();
Тут будет один неприятный момент, только один процесс должен будет закрыть удалить семафор. Тогда второй гарантированно получит тут ошибку

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/allocator/LinearAllocator.hpp
> +        return m_shmem->store<value_type>(count);
Метод allocate не должен вызывать конструктор, а store вызывает

2020-04-21 08:11 UTC, a-badin commented on hw5/shmem/include/shmem/allocator/LinearAllocator.hpp
> +        m_shmem->free(ptr, count);
deallocate не должен вызывать деструтор, как это делает free у SharedMemory

2020-04-21 08:11 UTC, a-badin commented on hw5/examples/simple/main.cpp
> +    shmem::Map<std::string, std::string, 2> map;
Такой словарь не будет работать. Пока у вас строки маленькие - они за счет small object optimization попадают в тот же адрес, где находится сам std::string - то есть в общую память. Как только вы сделаете строки длинее (20 символов) std::string алоцирует буфер в куче и строчки идут туда.

2020-04-25 11:12 UTC, babayanv commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        reinterpret_cast<T*>(mmap_ptr),
Сделал

2020-04-25 11:15 UTC, babayanv commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +    const long c_page_size = ::sysconf(_SC_PAGE_SIZE);
Незачем. Заменил на содержимое там, где использовал

2020-04-25 11:22 UTC, babayanv commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        return *m_unused_memory_begin_ptr;
Чтобы не мучаться с семантикой этих двух указателей и не быть вынужденным постоянно помнить, где что лежит.
m_unused_memory_begin_ptr - это указатель на адрес, в котором лежит указатель на начало свободного участка памяти
*m_unused_memory_begin_ptr - это указатель на начало свободного участка.

В методах класса обращение идет как к одному, так и к другому указателям. Возвращаясь к этому коду спустя 1.5 недели без них я бы запутался, где что должно быть, и потратил бы на это лишнее время.

2020-04-25 11:26 UTC, babayanv commented on hw5/shmem/include/shmem/allocator/LinearAllocator.hpp
> +    constexpr LinearAllocator(const LinearAllocator<U>& other)
Убрал верхний

2020-04-25 11:29 UTC, babayanv commented on hw5/shmem/include/shmem/container/Map.hpp
> +    using key_type = Key;
Сделал для удобства поддержания этого дела. Если в будущем внутренный тип ключа станет гетерогенным, то есть не просто равным Key, его легко можно будет заменить в 1 строчке.

Убрал, так как сейчас это не так.

2020-04-25 11:47 UTC, babayanv commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        , m_unused_memory_begin_ptr(
Вынес в тело

2020-04-25 16:50 UTC, babayanv commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +    boundary_ptr* m_unused_memory_begin_ptr;
И правда, так вышло удобнее.

2020-04-25 16:51 UTC, babayanv commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        return *m_unused_memory_begin_ptr;
После того, как начал хранить структуру вместо 2 указателей, стало не актуально, поэтому удалил

2020-04-25 16:58 UTC, babayanv commented on hw5/shmem/include/shmem/container/Map.hpp
> +template <class Key, class T, uint AccessorsCount = 1, class Compare = std::less<Key>>
Убрал этот параметр

2020-04-25 17:09 UTC, babayanv commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +    constexpr Semaphore(uint accessors_count = 1)
Вообще, constexpr конструктор позволяет проинициализировать создаваемый объект на этапе компиляции. Но так как в какой-то момент тело этого конструктора стало не пустым, то здесь он не делает ничего.

Убрал.

2020-04-25 17:23 UTC, babayanv commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +            destroy();
Сделал destroy - noexcet методом, который игнорируешь возврат sem_destroy

2020-04-25 21:52 UTC, babayanv commented
Я вообще не понял по поводу allocator_traits. Зачем мне с помощью него что-то оборачивать, когда std::map и так обернет переданный в него аллокатор внутри себя?

LinearAllocator уже по сути является прокси для SharedMemory. Я не могу просто обернуть SharedMemory в allocator_traits, потому как Allocator может оперировать только одним типом - value_type, соответственно, все выдаваемые им адреса будут кратны sizeof(value_type). А SharedMemory должен уметь аллоцировать память под разные типы.

Для этого класс SharedMemory должен выглядеть примерно так:
class SharedMemory {
    template <class AllocatedType>
    AllocatedType* allocate(size_t n) {...}
    ...
};
^ - позволяет аллоцировать память разных типов => разного размера

А std::allocator_traits требует чего-то такого:
template <class T>
class Allocator {
    T* allocate(size_t n) {...}
    ...
};
^ - позволяет аллоцировать память только для 1 типа => размера, кратного размеру этого типа

так как перегрузка по одно лишь возвращаемому значению в качестве признака разделения невозможна, SHaredMemory  в таком виде просто сунуть в allocator_traits нельзя
Для того, чтобы SharedMemory можно было использовать как аллокатор, есть класс-прокся LinearAllocator, который ужесточает аллоцируемый тип до 1 типа. Оборачивать его еще раз в allocator_traits в моейм коде - бессмысленно, он и так выполняет свою функцию. Более того, std::map сам сделает это внутри себя

2020-04-25 22:02 UTC, babayanv commented on hw5/shmem/include/shmem/allocator/LinearAllocator.hpp
> +        return m_shmem->store<value_type>(count);
Не знал, теперь заню)
Разделил на 2 метода

2020-04-25 22:02 UTC, babayanv commented on hw5/shmem/include/shmem/allocator/LinearAllocator.hpp
> +        m_shmem->free(ptr, count);
Тоже разделил на 2 метода

2020-04-27 13:59 UTC, babayanv commented on hw5/examples/simple/main.cpp
> +    shmem::Map<std::string, std::string, 2> map;
Сделал путем выноса SharedMemory за пределы контейнера. Теперь, чтобы Map работал для динамических объектов, необходимо отдельно создать экземпляр SharedMemory и вручную прокидывать его в emplace для конструктора хранимого типа

2020-04-27 17:55 UTC, a-badin commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +            destroy();
Не вариант уничтожит первый

2020-04-29 13:10 UTC, babayanv commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +            destroy();
Сделал так, чтобы семафор было необъодимо уничтожать вручную. Аналогично для Map и SharedMemory

2020-04-29 13:11 UTC, babayanv commented on hw5/examples/simple/main.cpp
> +    shmem::Map<std::string, std::string, 2> map;
\+ Добавил лок на allocate и deallocate в SharedMemory, тк он теперь создается вне контейнера и может между ними шариться

2020-04-30 14:22 UTC, a-badin approved these changes

2020-04-30 14:22 UTC, a-badin commented on hw5/shmem/include/shmem/utils/sync/Semaphore.hpp
> +            destroy();
Не нашел метод

2020-04-30 14:22 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        if (m_boundaries->m_begin + count * sizeof(T) >= m_boundaries->m_end)
Это тоже надо было захватить, m_begin то меняется

2020-04-30 14:22 UTC, a-badin commented on hw5/shmem/include/shmem/SharedMemory.hpp
> +        utils::SemaphoreLock lock(*m_semaphore_ptr);
и тут соответственно

2020-04-30 14:22 UTC, merged