hw6 done
babayanv/tp-advcpp pull request #6
Opened 2020-05-15 16:57 UTC by babayanv

2020-05-15 17:17 UTC, smirnov-vs requested changes
сигналы, нагрузочное тестирование
таймауты
посмотреть, что все условия дз выполнены

2020-05-15 17:17 UTC, smirnov-vs commented on hw6/examples/server/my_server.hpp
> +        validate_method(request.method) && validate_path(request.path) && validate_version(request.version);
enum

2020-05-15 17:17 UTC, smirnov-vs commented on hw6/http/include/http/server/server.hpp
> +                        ServerWorker sw(m_fd, m_done, [this](const network::HttpRequest& request) { return static_cast<Derived*>(this)->on_request(request); } );
fix

2020-05-15 17:17 UTC, smirnov-vs commented on hw6/http/src/network/connection.cpp
> +        ssize_t bytes_written = ::sendfile(m_sock_fd, file_fd, nullptr, fs::file_size(file_path));
тут ошибка

2020-05-15 17:17 UTC, smirnov-vs commented on hw6/http/src/network/protocol/http_request.cpp
> +        decoded_str.replace(url_encode_pos, 3, 1, url_decode);
+=

2020-05-15 17:17 UTC, smirnov-vs commented on hw6/http/src/network/protocol/http_request.cpp
> +        m_request.query_params.emplace(query_param_name, query_param_value);
unescape

2020-05-28 02:59 UTC, babayanv commented on hw6/http/src/network/protocol/http_request.cpp
> +        m_request.query_params.emplace(query_param_name, query_param_value);
Сделал так, чтобы автоматически это делалось при парсинге пути и параметров запроса

2020-05-28 02:59 UTC, babayanv commented on hw6/http/src/network/protocol/http_request.cpp
> +        decoded_str.replace(url_encode_pos, 3, 1, url_decode);
Сделал

2020-05-28 02:59 UTC, babayanv commented on hw6/http/include/http/server/server.hpp
> +                        ServerWorker sw(m_fd, m_done, [this](const network::HttpRequest& request) { return static_cast<Derived*>(this)->on_request(request); } );
Пофиксил, теперь без шаблонов

2020-05-29 12:53 UTC, babayanv commented on hw6/http/src/network/connection.cpp
> +        ssize_t bytes_written = ::sendfile(m_sock_fd, file_fd, nullptr, fs::file_size(file_path));
Как я понял, проблема в том, что nullptr передаю третьим аргументом. Из-за этого, если весь файл не передался за раз, то файл снова будет отправлен сначала

Исправил, добавил переменную с офсетом

2020-05-29 13:05 UTC, babayanv commented
Нагрузочное тестирование - на вход идет файл размером около 1 мб
![Screenshot at 2020-05-29 15-51-08](https://user-images.githubusercontent.com/32416153/83262599-f50b2900-a1c5-11ea-81f3-c6f33d1da745.png)

2020-05-29 13:27 UTC, babayanv commented on hw6/examples/server/my_server.hpp
> +        validate_method(request.method) && validate_path(request.path) && validate_version(request.version);
Вот тут не понял/не помню, как тут можно заюзать enum.

Если хотя бы одно из полей не провалидировано, то запрос можно считать невалидным. Соответственно, валидировать дальше не надо.

2020-06-02 17:01 UTC, smirnov-vs commented
надо обсудить для зачета

2020-06-04 13:36 UTC, smirnov-vs reviewed
keep-alive
холостой + keep-alive

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/examples/server/my_server/my_server.cpp
> +        enqueue_send_file(file_path); // entered file will be sent after the returned response
продумать

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/examples/server/my_server/my_server.hpp
> +#include "../../../log/include/log/Logger.hpp"
cmake

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/http/src/network/connection.cpp
> +        std::string chunk(1024, '\0');
вынести из цикла

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/http/src/network/protocol/http.cpp
> +mime_type::value_type determine_content_type(const std::string_view& file_path) {
по значению

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/http/src/network/protocol/http_response.cpp
> +    for (auto& i : headers)
structured binding

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/http/src/server/server.cpp
> +        close();
лишнее

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/http/src/server/server_worker.cpp
> +        add_epoll(conn_fd, EPOLLIN | EPOLLEXCLUSIVE);
разобраться

2020-06-04 13:36 UTC, smirnov-vs commented on hw6/http/src/utils/coroutine.cpp
> +        getcontext(&ctx);
getcontext выше всех

2020-06-05 01:18 UTC, babayanv commented on hw6/examples/server/my_server/my_server.cpp
> +        enqueue_send_file(file_path); // entered file will be sent after the returned response
Добавил поле в Response с именами файлов

2020-06-05 01:23 UTC, babayanv commented on hw6/examples/server/my_server/my_server.hpp
> +#include "../../../log/include/log/Logger.hpp"
Сделал

2020-06-05 01:26 UTC, babayanv commented on hw6/http/src/network/protocol/http.cpp
> +mime_type::value_type determine_content_type(const std::string_view& file_path) {
Сделал

2020-06-05 01:28 UTC, babayanv commented on hw6/http/src/network/protocol/http_response.cpp
> +    for (auto& i : headers)
Сделал

2020-06-05 01:30 UTC, babayanv commented on hw6/http/src/server/server.cpp
> +        close();
Убрал

2020-06-05 01:31 UTC, babayanv commented on hw6/http/src/utils/coroutine.cpp
> +        getcontext(&ctx);
Переместил

2020-06-05 04:01 UTC, babayanv commented on hw6/http/src/server/server_worker.cpp
> +        add_epoll(conn_fd, EPOLLIN | EPOLLEXCLUSIVE);
EPOLLEXCLUSIVE здесь не нужен, 1 клиент попадает только на 1 еполл

2020-06-05 09:08 UTC, babayanv commented
![file](https://user-images.githubusercontent.com/32416153/83858481-3d29ce80-a725-11ea-8f77-3d843df77206.png)
![no_file](https://user-images.githubusercontent.com/32416153/83858485-3f8c2880-a725-11ea-8ccc-eeb9ddb9f3d9.png)
![no_file-k](https://user-images.githubusercontent.com/32416153/83858490-4155ec00-a725-11ea-8445-51ff32501681.png)

2020-06-05 10:45 UTC, smirnov-vs approved these changes

2020-09-20 20:29 UTC, merged